services:
  db_cron_backup_cloud:
    image: shuffle4117/sql-supercronic-gcloud-backup:1.0.0
    volumes:      
      - ./backups:/backups:ro
    environment:    
      CRON_TIME: "0 4 * * *" # every day at 4 a.m.
      GCLOUD_STORAGE_CREDENTIALS_PATH: /run/secrets/backend_gcloud_creds_storage
      IN_CONTAINER_BACKUPS_DIR: /backups
      BACKUP_FILE_NAME: FILE.sql.gz
      BACKUP_FILE_BLOB_DIR_PATH: "" # empty = at root of bucket
      BUCKET_NAME: BUCKETNAME
      MAX_BACKUP_FILES: 360 
      OVERRIDE_FILES: false # overwrite identical files
      TZ: Europe/Berlin # timezone for correct log time
    secrets:
      - backend_gcloud_creds_storage

secrets:
  backend_gcloud_creds_storage:
    # external: true  
    file: <path>
      